---
title: "Main analysis"
author: "me medesimo"
date: "2025-08-20"
output: html_document
---

```{r setup}
source("ensemble.R")
source("fairness.R")
source("uncertainties.R")
source("data/syntethic_datasets/02_synthetic_data.R")
# adult_data <- read.csv("data/real_datasets/adult/adult.data", header = FALSE, strip.white = TRUE, na.strings = "?")
```

```{r}
# Prepara train/test split
set.seed(123)
train_indices <- sample(nrow(sd1_data), 0.8 * nrow(sd1_data))
train_data <- sd2_data[train_indices, ]
test_data <- sd2_data[-train_indices, ]
```



```{r}
ensemble_models <- create_uncertainty_ensemble(train_data, 'Y')
```

group_metrics <- calculate_group_metrics(ensemble_models, test_data, sensitive_attr = "G")
print(group_metrics)


```{r}
uncertainties <- calculate_uncertainties(ensemble_models, test_data)
fairness_measures <- calculate_uncertainty_fairness(uncertainties, test_data$G)
print(fairness_measures)
```

print(uncertainties)

sensitive_attr <- test_data$G

```{r}
# fairness <- calculate_fairness_measures(uncertainties, sensitive_attr)
fairness_epistemic <- calculate_fairness_measures(uncertainties$epistemic, sensitive_attr)
fairness_aleatoric <- calculate_fairness_measures(uncertainties$aleatoric, sensitive_attr)
fairness_predictive <- calculate_fairness_measures(uncertainties$predictive, sensitive_attr)
```

print(fairness_epistemic)
print(fairness_aleatoric)
print(fairness_predictive)


