---
title: "Main analysis"
author: "me medesimo"
date: "2025-08-20"
output: html_document
---

```{r setup}
source("bnn(b).R")
source("bnn(b)(m).R")
source("fairness.R")
source("uncertainties.R")
source("data/syntethic_datasets/01_synthetic_data.R")
```

```{r}
# Prepara train/test split
set.seed(42)
train_indices <- sample(nrow(sd1_data), 0.8 * nrow(sd1_data))
train_data <- sd1_data[train_indices, ]
test_data <- sd1_data[-train_indices, ]
```


```{r}
train_data <- train_data %>% rename(y = Y) # rinominato y piccolo perche pacchetto stan richiede cosi
train_data$y <- as.numeric(train_data$y)
train_data$G <- as.numeric(train_data$G)
test_data <- test_data %>% rename(y = Y) # rinominato y piccolo perche pacchetto stan
test_data$y <- as.numeric(test_data$y)
test_data$G <- as.numeric(test_data$G)
uncertainty_bnn <- create_uncertainty_ensemble(train_data, 'y')
```

```{r}
# Opzione 2: Calcolo completo con ensemble
accuracy_results <- calculate_ensemble_accuracy(uncertainty_bnn, test_data, 'y')
```


```{r}
uncertainties <- calculate_uncertainties(create_uncertainty_bnn, test_data)
fairness_measures <- calculate_uncertainty_fairness(uncertainties, test_data$G)
print(fairness_measures)
```


sensitive_attr <- test_data$G

```{r}
# fairness <- calculate_fairness_measures(uncertainties, sensitive_attr)
fairness_epistemic <- calculate_fairness_measures(uncertainties$epistemic, sensitive_attr)
fairness_aleatoric <- calculate_fairness_measures(uncertainties$aleatoric, sensitive_attr)
fairness_predictive <- calculate_fairness_measures(uncertainties$predictive, sensitive_attr)

```


