---
title: "Main analysis"
author: "me medesimo"
date: "2025-08-20"
output: html_document
---

```{r setup}
library(readr)

source("bnn.R")
source("gigi_puzza.R")
source("fairness.R")
source("uncertainties.R")
train_data <- read_csv('data/real_datasets/adult/adult.data', col_names = FALSE, show_col_types = FALSE)
test_data <- read_csv('data/real_datasets/adult/adult.test', skip = 1, col_names = FALSE, show_col_types = FALSE)
```

```{r}
train_data <- train_data %>% rename(y = X15) # rinominato y piccolo perche pacchetto stan richiede cosi

test_data <- test_data %>% rename(y = X15) # rinominato y piccolo perche pacchetto stan

# Convertire la colonna 'y' in binario
train_data$y <- ifelse(trimws(train_data$y) == "<=50K", 0, 1)
test_data$y <- ifelse(trimws(test_data$y) == "<=50K", 0, 1)

train_data$y <- as.numeric(train_data$y)
test_data$y <- as.numeric(test_data$y)

uncertainty_bnn <- create_uncertainty_ensemble(train_data, 'y')
```

```{r}
# Opzione 2: Calcolo completo con ensemble
accuracy_results <- calculate_ensemble_accuracy(uncertainty_bnn, test_data, 'y')
```

```{r}
results <- calculate_ensemble_metrics_by_group(
  models = uncertainty_bnn,
  test_data = test_data,
  target_col = "y",
  group_col = "G", 
  levels_order = c("0", "1"),
  positive_class = 2
)

# Access results
results$ensemble_metrics_by_group  # TPR, FPR, etc. by group
results$fairness_measures          # All fairness ratios
results$confusion_matrices         # TP, TN, FP, FN counts
```

```{r}
uncertainties <- calculate_uncertainties(uncertainty_bnn, test_data)
fairness_measures <- calculate_uncertainty_fairness(uncertainties, test_data$G)
print(fairness_measures)
```



