---
title: "Main analysis"
author: "me medesimo"
date: "2025-08-20"
output: html_document
---

```{r setup}
source("ensemble_random.R")
source("ensemble_accuracy.R")
source("fairness.R")
source("uncertainties.R")
source("data/syntethic_datasets/01_synthetic_data.R")
```

```{r}
# Prepara train/test split
set.seed(3)
train_indices <- sample(nrow(sd1_data), 0.8 * nrow(sd1_data))
train_data <- sd1_data[train_indices, ]
test_data <- sd1_data[-train_indices, ]
```

```{r}
train_data <- train_data %>% rename(y = Y) # rinominato y piccolo perche pacchetto stan richiede cosi
test_data <- test_data %>% rename(y = Y) # rinominato y piccolo perche pacchetto stan
```

```{r}
# 1. CONVERTI Y IN FATTORE PER CLASSIFICAZIONE
train_data$y <- as.factor(train_data$y)  # Converte in fattore per classificazione
test_data$y <- as.factor(test_data$y)    # Converte in fattore per classificazione
```

```{r}
rf <- create_uncertainty_ensemble(train_data, "y")
```

```{r}
# 4. CALCOLA L'ACCURACY (USA 'y' NON 'Y'!)
accuracy_results <- calculate_rf_ensemble_accuracy(rf, test_data, 'y')
```
```{r}
accuracy_group <- calculate_rf_group_accuracy(rf, test_data, "G", target_col = "y")
```

```{r}
uncertainties <- calculate_uncertainties(rf, test_data)
group_uncertainties <- calculate_group_uncertainties(rf, test_data, "G")
```

```{r}
uncertainties <- calculate_uncertainties(create_uncertainty_bnn, test_data)
fairness_measures <- calculate_uncertainty_fairness(uncertainties, test_data$G)
print(fairness_measures)
```


sensitive_attr <- test_data$G

```{r}
# fairness <- calculate_fairness_measures(uncertainties, sensitive_attr)
fairness_epistemic <- calculate_fairness_measures(uncertainties$epistemic, sensitive_attr)
fairness_aleatoric <- calculate_fairness_measures(uncertainties$aleatoric, sensitive_attr)
fairness_predictive <- calculate_fairness_measures(uncertainties$predictive, sensitive_attr)

```


